import Head from "next/head"

import { type NextPage } from "next"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Genésio Da Silva Pacheco</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div></div>
      </main>
    </>
  )
}

export default Home
